services:
  # - type: web
  #   name: 'hikma-health-admin'
  #   runtime: node
  #   buildCommand: npm run build
  #   startCommand: npm run start
  #   envVars:
  #     - key: HIKMA_API
  #       value: "VALUE_HERE"
  #
  - type: web
    name: "hikma-health-aiproxy"
    runtime: node
    # Uncomment if you want to deploy to the free tier first.
    # NOTE: free tier has degraded performance making it unusable in real world settings
    # plan: free
    buildCommand: pnpm install -w; just install-build-aiproxy
    startCommand: just start-aiproxy
    buildFilter:
      ignoredPaths:
        - apps/mobile/**
        - apps/server/**
        - apps/local-hub/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hikma-health-db
          property: connectionString
      - key: DATABASE_SSL_OPTIONS
        value: '{"rejectUnauthorized":false}'
      - key: NODE_ENV
        value: "production"

  - type: web
    name: "hikma-health-server"
    runtime: node
    # Uncomment if you want to deploy to the free tier first.
    # NOTE: free tier has degraded performance making it unusable in real world settings
    # plan: free
    buildCommand: pnpm install -w; just install-build-server
    startCommand: just start-server
    buildFilter:
      ignoredPaths:
        - apps/mobile/**
        - apps/aiproxy/**
        - apps/local-hub/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hikma-health-db
          property: connectionString
      - key: DATABASE_SSL_OPTIONS
        value: '{"rejectUnauthorized":false}'

databases:
  - name: "hikma-health-db"
    # Uncomment this line to use the free tier of the database
    # NOTE: FREE DATABASES ARE DELETED AFTER 90 DAYS!!! Remember NEVER to use a free database after for real patient data.
    # plan: free
    databaseName: hhdb
    user: hikma
    # highAvailability:
    # enabled: true
# Define any additional services or database configurations if needed
