/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as AppUsersIndexRouteImport } from './routes/app/users.index'
import { Route as AppPrescriptionsIndexRouteImport } from './routes/app/prescriptions.index'
import { Route as AppPatientsIndexRouteImport } from './routes/app/patients.index'
import { Route as AppEventFormsIndexRouteImport } from './routes/app/event-forms.index'
import { Route as AppClinicsIndexRouteImport } from './routes/app/clinics.index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/app/appointments.index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AppSettingsRegisterMobileAppRouteImport } from './routes/app/settings.register-mobile-app'
import { Route as AppSettingsConfigurationsRouteImport } from './routes/app/settings.configurations'
import { Route as AppPatientsRegisterRouteImport } from './routes/app/patients.register'
import { Route as AppPatientsCustomizeRegistrationFormRouteImport } from './routes/app/patients.customize-registration-form'
import { Route as AppDataEventsRouteImport } from './routes/app/data.events'
import { Route as ApiV2SyncRouteImport } from './routes/api/v2.sync'
import { Route as AppPatientsSplatIndexRouteImport } from './routes/app/patients.$.index'
import { Route as AppInventoryDrugCatalogueIndexRouteImport } from './routes/app/inventory/drug-catalogue.index'
import { Route as AppInventoryClinicInventoryIndexRouteImport } from './routes/app/inventory/clinic-inventory.index'
import { Route as AppClinicsSplatIndexRouteImport } from './routes/app/clinics.$.index'
import { Route as AppUsersManagePermissionsSplatRouteImport } from './routes/app/users.manage-permissions.$'
import { Route as AppUsersEditSplatRouteImport } from './routes/app/users.edit.$'
import { Route as AppPrescriptionsEditSplatRouteImport } from './routes/app/prescriptions.edit.$'
import { Route as AppEventFormsEditSplatRouteImport } from './routes/app/event-forms.edit.$'
import { Route as AppClinicsEditSplatRouteImport } from './routes/app/clinics.edit.$'
import { Route as AppAppointmentsEditSplatRouteImport } from './routes/app/appointments.edit.$'
import { Route as AppInventoryDrugCatalogueEditSplatRouteImport } from './routes/app/inventory/drug-catalogue.edit.$'
import { Route as AppInventoryClinicInventoryDrugEditSplatRouteImport } from './routes/app/inventory/clinic-inventory.drug.edit.$'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsIndexRoute = AppPrescriptionsIndexRouteImport.update({
  id: '/prescriptions/',
  path: '/prescriptions/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventFormsIndexRoute = AppEventFormsIndexRouteImport.update({
  id: '/event-forms/',
  path: '/event-forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsIndexRoute = AppClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRegisterMobileAppRoute =
  AppSettingsRegisterMobileAppRouteImport.update({
    id: '/settings/register-mobile-app',
    path: '/settings/register-mobile-app',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsConfigurationsRoute =
  AppSettingsConfigurationsRouteImport.update({
    id: '/settings/configurations',
    path: '/settings/configurations',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsRegisterRoute = AppPatientsRegisterRouteImport.update({
  id: '/patients/register',
  path: '/patients/register',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsCustomizeRegistrationFormRoute =
  AppPatientsCustomizeRegistrationFormRouteImport.update({
    id: '/patients/customize-registration-form',
    path: '/patients/customize-registration-form',
    getParentRoute: () => AppRoute,
  } as any)
const AppDataEventsRoute = AppDataEventsRouteImport.update({
  id: '/data/events',
  path: '/data/events',
  getParentRoute: () => AppRoute,
} as any)
const ApiV2SyncRoute = ApiV2SyncRouteImport.update({
  id: '/api/v2/sync',
  path: '/api/v2/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsSplatIndexRoute = AppPatientsSplatIndexRouteImport.update({
  id: '/patients/$/',
  path: '/patients/$/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryDrugCatalogueIndexRoute =
  AppInventoryDrugCatalogueIndexRouteImport.update({
    id: '/inventory/drug-catalogue/',
    path: '/inventory/drug-catalogue/',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryClinicInventoryIndexRoute =
  AppInventoryClinicInventoryIndexRouteImport.update({
    id: '/inventory/clinic-inventory/',
    path: '/inventory/clinic-inventory/',
    getParentRoute: () => AppRoute,
  } as any)
const AppClinicsSplatIndexRoute = AppClinicsSplatIndexRouteImport.update({
  id: '/clinics/$/',
  path: '/clinics/$/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersManagePermissionsSplatRoute =
  AppUsersManagePermissionsSplatRouteImport.update({
    id: '/users/manage-permissions/$',
    path: '/users/manage-permissions/$',
    getParentRoute: () => AppRoute,
  } as any)
const AppUsersEditSplatRoute = AppUsersEditSplatRouteImport.update({
  id: '/users/edit/$',
  path: '/users/edit/$',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsEditSplatRoute =
  AppPrescriptionsEditSplatRouteImport.update({
    id: '/prescriptions/edit/$',
    path: '/prescriptions/edit/$',
    getParentRoute: () => AppRoute,
  } as any)
const AppEventFormsEditSplatRoute = AppEventFormsEditSplatRouteImport.update({
  id: '/event-forms/edit/$',
  path: '/event-forms/edit/$',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsEditSplatRoute = AppClinicsEditSplatRouteImport.update({
  id: '/clinics/edit/$',
  path: '/clinics/edit/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsEditSplatRoute =
  AppAppointmentsEditSplatRouteImport.update({
    id: '/appointments/edit/$',
    path: '/appointments/edit/$',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryDrugCatalogueEditSplatRoute =
  AppInventoryDrugCatalogueEditSplatRouteImport.update({
    id: '/inventory/drug-catalogue/edit/$',
    path: '/inventory/drug-catalogue/edit/$',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryClinicInventoryDrugEditSplatRoute =
  AppInventoryClinicInventoryDrugEditSplatRouteImport.update({
    id: '/inventory/clinic-inventory/drug/edit/$',
    path: '/inventory/clinic-inventory/drug/edit/$',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/app/': typeof AppIndexRoute
  '/api/v2/sync': typeof ApiV2SyncRoute
  '/app/data/events': typeof AppDataEventsRoute
  '/app/patients/customize-registration-form': typeof AppPatientsCustomizeRegistrationFormRoute
  '/app/patients/register': typeof AppPatientsRegisterRoute
  '/app/settings/configurations': typeof AppSettingsConfigurationsRoute
  '/app/settings/register-mobile-app': typeof AppSettingsRegisterMobileAppRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
  '/app/clinics': typeof AppClinicsIndexRoute
  '/app/event-forms': typeof AppEventFormsIndexRoute
  '/app/patients': typeof AppPatientsIndexRoute
  '/app/prescriptions': typeof AppPrescriptionsIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/appointments/edit/$': typeof AppAppointmentsEditSplatRoute
  '/app/clinics/edit/$': typeof AppClinicsEditSplatRoute
  '/app/event-forms/edit/$': typeof AppEventFormsEditSplatRoute
  '/app/prescriptions/edit/$': typeof AppPrescriptionsEditSplatRoute
  '/app/users/edit/$': typeof AppUsersEditSplatRoute
  '/app/users/manage-permissions/$': typeof AppUsersManagePermissionsSplatRoute
  '/app/clinics/$': typeof AppClinicsSplatIndexRoute
  '/app/inventory/clinic-inventory': typeof AppInventoryClinicInventoryIndexRoute
  '/app/inventory/drug-catalogue': typeof AppInventoryDrugCatalogueIndexRoute
  '/app/patients/$': typeof AppPatientsSplatIndexRoute
  '/app/inventory/drug-catalogue/edit/$': typeof AppInventoryDrugCatalogueEditSplatRoute
  '/app/inventory/clinic-inventory/drug/edit/$': typeof AppInventoryClinicInventoryDrugEditSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/app': typeof AppIndexRoute
  '/api/v2/sync': typeof ApiV2SyncRoute
  '/app/data/events': typeof AppDataEventsRoute
  '/app/patients/customize-registration-form': typeof AppPatientsCustomizeRegistrationFormRoute
  '/app/patients/register': typeof AppPatientsRegisterRoute
  '/app/settings/configurations': typeof AppSettingsConfigurationsRoute
  '/app/settings/register-mobile-app': typeof AppSettingsRegisterMobileAppRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
  '/app/clinics': typeof AppClinicsIndexRoute
  '/app/event-forms': typeof AppEventFormsIndexRoute
  '/app/patients': typeof AppPatientsIndexRoute
  '/app/prescriptions': typeof AppPrescriptionsIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/appointments/edit/$': typeof AppAppointmentsEditSplatRoute
  '/app/clinics/edit/$': typeof AppClinicsEditSplatRoute
  '/app/event-forms/edit/$': typeof AppEventFormsEditSplatRoute
  '/app/prescriptions/edit/$': typeof AppPrescriptionsEditSplatRoute
  '/app/users/edit/$': typeof AppUsersEditSplatRoute
  '/app/users/manage-permissions/$': typeof AppUsersManagePermissionsSplatRoute
  '/app/clinics/$': typeof AppClinicsSplatIndexRoute
  '/app/inventory/clinic-inventory': typeof AppInventoryClinicInventoryIndexRoute
  '/app/inventory/drug-catalogue': typeof AppInventoryDrugCatalogueIndexRoute
  '/app/patients/$': typeof AppPatientsSplatIndexRoute
  '/app/inventory/drug-catalogue/edit/$': typeof AppInventoryDrugCatalogueEditSplatRoute
  '/app/inventory/clinic-inventory/drug/edit/$': typeof AppInventoryClinicInventoryDrugEditSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/app/': typeof AppIndexRoute
  '/api/v2/sync': typeof ApiV2SyncRoute
  '/app/data/events': typeof AppDataEventsRoute
  '/app/patients/customize-registration-form': typeof AppPatientsCustomizeRegistrationFormRoute
  '/app/patients/register': typeof AppPatientsRegisterRoute
  '/app/settings/configurations': typeof AppSettingsConfigurationsRoute
  '/app/settings/register-mobile-app': typeof AppSettingsRegisterMobileAppRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/appointments/': typeof AppAppointmentsIndexRoute
  '/app/clinics/': typeof AppClinicsIndexRoute
  '/app/event-forms/': typeof AppEventFormsIndexRoute
  '/app/patients/': typeof AppPatientsIndexRoute
  '/app/prescriptions/': typeof AppPrescriptionsIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/appointments/edit/$': typeof AppAppointmentsEditSplatRoute
  '/app/clinics/edit/$': typeof AppClinicsEditSplatRoute
  '/app/event-forms/edit/$': typeof AppEventFormsEditSplatRoute
  '/app/prescriptions/edit/$': typeof AppPrescriptionsEditSplatRoute
  '/app/users/edit/$': typeof AppUsersEditSplatRoute
  '/app/users/manage-permissions/$': typeof AppUsersManagePermissionsSplatRoute
  '/app/clinics/$/': typeof AppClinicsSplatIndexRoute
  '/app/inventory/clinic-inventory/': typeof AppInventoryClinicInventoryIndexRoute
  '/app/inventory/drug-catalogue/': typeof AppInventoryDrugCatalogueIndexRoute
  '/app/patients/$/': typeof AppPatientsSplatIndexRoute
  '/app/inventory/drug-catalogue/edit/$': typeof AppInventoryDrugCatalogueEditSplatRoute
  '/app/inventory/clinic-inventory/drug/edit/$': typeof AppInventoryClinicInventoryDrugEditSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/app/'
    | '/api/v2/sync'
    | '/app/data/events'
    | '/app/patients/customize-registration-form'
    | '/app/patients/register'
    | '/app/settings/configurations'
    | '/app/settings/register-mobile-app'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/appointments'
    | '/app/clinics'
    | '/app/event-forms'
    | '/app/patients'
    | '/app/prescriptions'
    | '/app/users'
    | '/app/appointments/edit/$'
    | '/app/clinics/edit/$'
    | '/app/event-forms/edit/$'
    | '/app/prescriptions/edit/$'
    | '/app/users/edit/$'
    | '/app/users/manage-permissions/$'
    | '/app/clinics/$'
    | '/app/inventory/clinic-inventory'
    | '/app/inventory/drug-catalogue'
    | '/app/patients/$'
    | '/app/inventory/drug-catalogue/edit/$'
    | '/app/inventory/clinic-inventory/drug/edit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/app'
    | '/api/v2/sync'
    | '/app/data/events'
    | '/app/patients/customize-registration-form'
    | '/app/patients/register'
    | '/app/settings/configurations'
    | '/app/settings/register-mobile-app'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/appointments'
    | '/app/clinics'
    | '/app/event-forms'
    | '/app/patients'
    | '/app/prescriptions'
    | '/app/users'
    | '/app/appointments/edit/$'
    | '/app/clinics/edit/$'
    | '/app/event-forms/edit/$'
    | '/app/prescriptions/edit/$'
    | '/app/users/edit/$'
    | '/app/users/manage-permissions/$'
    | '/app/clinics/$'
    | '/app/inventory/clinic-inventory'
    | '/app/inventory/drug-catalogue'
    | '/app/patients/$'
    | '/app/inventory/drug-catalogue/edit/$'
    | '/app/inventory/clinic-inventory/drug/edit/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/app/'
    | '/api/v2/sync'
    | '/app/data/events'
    | '/app/patients/customize-registration-form'
    | '/app/patients/register'
    | '/app/settings/configurations'
    | '/app/settings/register-mobile-app'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/appointments/'
    | '/app/clinics/'
    | '/app/event-forms/'
    | '/app/patients/'
    | '/app/prescriptions/'
    | '/app/users/'
    | '/app/appointments/edit/$'
    | '/app/clinics/edit/$'
    | '/app/event-forms/edit/$'
    | '/app/prescriptions/edit/$'
    | '/app/users/edit/$'
    | '/app/users/manage-permissions/$'
    | '/app/clinics/$/'
    | '/app/inventory/clinic-inventory/'
    | '/app/inventory/drug-catalogue/'
    | '/app/patients/$/'
    | '/app/inventory/drug-catalogue/edit/$'
    | '/app/inventory/clinic-inventory/drug/edit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiV2SyncRoute: typeof ApiV2SyncRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prescriptions/': {
      id: '/app/prescriptions/'
      path: '/prescriptions'
      fullPath: '/app/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/': {
      id: '/app/patients/'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/event-forms/': {
      id: '/app/event-forms/'
      path: '/event-forms'
      fullPath: '/app/event-forms'
      preLoaderRoute: typeof AppEventFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinics/': {
      id: '/app/clinics/'
      path: '/clinics'
      fullPath: '/app/clinics'
      preLoaderRoute: typeof AppClinicsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/': {
      id: '/app/appointments/'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/register-mobile-app': {
      id: '/app/settings/register-mobile-app'
      path: '/settings/register-mobile-app'
      fullPath: '/app/settings/register-mobile-app'
      preLoaderRoute: typeof AppSettingsRegisterMobileAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/configurations': {
      id: '/app/settings/configurations'
      path: '/settings/configurations'
      fullPath: '/app/settings/configurations'
      preLoaderRoute: typeof AppSettingsConfigurationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/register': {
      id: '/app/patients/register'
      path: '/patients/register'
      fullPath: '/app/patients/register'
      preLoaderRoute: typeof AppPatientsRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/customize-registration-form': {
      id: '/app/patients/customize-registration-form'
      path: '/patients/customize-registration-form'
      fullPath: '/app/patients/customize-registration-form'
      preLoaderRoute: typeof AppPatientsCustomizeRegistrationFormRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data/events': {
      id: '/app/data/events'
      path: '/data/events'
      fullPath: '/app/data/events'
      preLoaderRoute: typeof AppDataEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v2/sync': {
      id: '/api/v2/sync'
      path: '/api/v2/sync'
      fullPath: '/api/v2/sync'
      preLoaderRoute: typeof ApiV2SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/patients/$/': {
      id: '/app/patients/$/'
      path: '/patients/$'
      fullPath: '/app/patients/$'
      preLoaderRoute: typeof AppPatientsSplatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/drug-catalogue/': {
      id: '/app/inventory/drug-catalogue/'
      path: '/inventory/drug-catalogue'
      fullPath: '/app/inventory/drug-catalogue'
      preLoaderRoute: typeof AppInventoryDrugCatalogueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/clinic-inventory/': {
      id: '/app/inventory/clinic-inventory/'
      path: '/inventory/clinic-inventory'
      fullPath: '/app/inventory/clinic-inventory'
      preLoaderRoute: typeof AppInventoryClinicInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinics/$/': {
      id: '/app/clinics/$/'
      path: '/clinics/$'
      fullPath: '/app/clinics/$'
      preLoaderRoute: typeof AppClinicsSplatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/manage-permissions/$': {
      id: '/app/users/manage-permissions/$'
      path: '/users/manage-permissions/$'
      fullPath: '/app/users/manage-permissions/$'
      preLoaderRoute: typeof AppUsersManagePermissionsSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/edit/$': {
      id: '/app/users/edit/$'
      path: '/users/edit/$'
      fullPath: '/app/users/edit/$'
      preLoaderRoute: typeof AppUsersEditSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prescriptions/edit/$': {
      id: '/app/prescriptions/edit/$'
      path: '/prescriptions/edit/$'
      fullPath: '/app/prescriptions/edit/$'
      preLoaderRoute: typeof AppPrescriptionsEditSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/event-forms/edit/$': {
      id: '/app/event-forms/edit/$'
      path: '/event-forms/edit/$'
      fullPath: '/app/event-forms/edit/$'
      preLoaderRoute: typeof AppEventFormsEditSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinics/edit/$': {
      id: '/app/clinics/edit/$'
      path: '/clinics/edit/$'
      fullPath: '/app/clinics/edit/$'
      preLoaderRoute: typeof AppClinicsEditSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments/edit/$': {
      id: '/app/appointments/edit/$'
      path: '/appointments/edit/$'
      fullPath: '/app/appointments/edit/$'
      preLoaderRoute: typeof AppAppointmentsEditSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/drug-catalogue/edit/$': {
      id: '/app/inventory/drug-catalogue/edit/$'
      path: '/inventory/drug-catalogue/edit/$'
      fullPath: '/app/inventory/drug-catalogue/edit/$'
      preLoaderRoute: typeof AppInventoryDrugCatalogueEditSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/clinic-inventory/drug/edit/$': {
      id: '/app/inventory/clinic-inventory/drug/edit/$'
      path: '/inventory/clinic-inventory/drug/edit/$'
      fullPath: '/app/inventory/clinic-inventory/drug/edit/$'
      preLoaderRoute: typeof AppInventoryClinicInventoryDrugEditSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDataEventsRoute: typeof AppDataEventsRoute
  AppPatientsCustomizeRegistrationFormRoute: typeof AppPatientsCustomizeRegistrationFormRoute
  AppPatientsRegisterRoute: typeof AppPatientsRegisterRoute
  AppSettingsConfigurationsRoute: typeof AppSettingsConfigurationsRoute
  AppSettingsRegisterMobileAppRoute: typeof AppSettingsRegisterMobileAppRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppClinicsIndexRoute: typeof AppClinicsIndexRoute
  AppEventFormsIndexRoute: typeof AppEventFormsIndexRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppPrescriptionsIndexRoute: typeof AppPrescriptionsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppAppointmentsEditSplatRoute: typeof AppAppointmentsEditSplatRoute
  AppClinicsEditSplatRoute: typeof AppClinicsEditSplatRoute
  AppEventFormsEditSplatRoute: typeof AppEventFormsEditSplatRoute
  AppPrescriptionsEditSplatRoute: typeof AppPrescriptionsEditSplatRoute
  AppUsersEditSplatRoute: typeof AppUsersEditSplatRoute
  AppUsersManagePermissionsSplatRoute: typeof AppUsersManagePermissionsSplatRoute
  AppClinicsSplatIndexRoute: typeof AppClinicsSplatIndexRoute
  AppInventoryClinicInventoryIndexRoute: typeof AppInventoryClinicInventoryIndexRoute
  AppInventoryDrugCatalogueIndexRoute: typeof AppInventoryDrugCatalogueIndexRoute
  AppPatientsSplatIndexRoute: typeof AppPatientsSplatIndexRoute
  AppInventoryDrugCatalogueEditSplatRoute: typeof AppInventoryDrugCatalogueEditSplatRoute
  AppInventoryClinicInventoryDrugEditSplatRoute: typeof AppInventoryClinicInventoryDrugEditSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDataEventsRoute: AppDataEventsRoute,
  AppPatientsCustomizeRegistrationFormRoute:
    AppPatientsCustomizeRegistrationFormRoute,
  AppPatientsRegisterRoute: AppPatientsRegisterRoute,
  AppSettingsConfigurationsRoute: AppSettingsConfigurationsRoute,
  AppSettingsRegisterMobileAppRoute: AppSettingsRegisterMobileAppRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppClinicsIndexRoute: AppClinicsIndexRoute,
  AppEventFormsIndexRoute: AppEventFormsIndexRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppPrescriptionsIndexRoute: AppPrescriptionsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppAppointmentsEditSplatRoute: AppAppointmentsEditSplatRoute,
  AppClinicsEditSplatRoute: AppClinicsEditSplatRoute,
  AppEventFormsEditSplatRoute: AppEventFormsEditSplatRoute,
  AppPrescriptionsEditSplatRoute: AppPrescriptionsEditSplatRoute,
  AppUsersEditSplatRoute: AppUsersEditSplatRoute,
  AppUsersManagePermissionsSplatRoute: AppUsersManagePermissionsSplatRoute,
  AppClinicsSplatIndexRoute: AppClinicsSplatIndexRoute,
  AppInventoryClinicInventoryIndexRoute: AppInventoryClinicInventoryIndexRoute,
  AppInventoryDrugCatalogueIndexRoute: AppInventoryDrugCatalogueIndexRoute,
  AppPatientsSplatIndexRoute: AppPatientsSplatIndexRoute,
  AppInventoryDrugCatalogueEditSplatRoute:
    AppInventoryDrugCatalogueEditSplatRoute,
  AppInventoryClinicInventoryDrugEditSplatRoute:
    AppInventoryClinicInventoryDrugEditSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiV2SyncRoute: ApiV2SyncRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
