tasks:
  check-types:
    command: pnpm run check-types
    deps:
      - ^:check-types
  dev:
    args: run dev
    command: pnpm
    options:
      cache: false
    deps:
      - ^:dev
    preset: server
  lint:
    command: pnpm run lint
    deps:
      - ^:lint
