/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlembicVersion {
  version_num: string;
}

export interface AppConfig {
  created_at: Generated<Timestamp | null>;
  data_type: Generated<string>;
  display_name: string | null;
  id: Generated<string>;
  key: string;
  last_modified: Generated<Timestamp | null>;
  last_modified_by: string | null;
  namespace: string;
  updated_at: Generated<Timestamp | null>;
  value: Generated<string | null>;
}

export interface Appointments {
  clinic_id: string;
  created_at: Timestamp;
  current_visit_id: string;
  deleted_at: Timestamp | null;
  departments: Generated<Json>;
  duration: number;
  fulfilled_visit_id: string | null;
  id: string;
  is_deleted: boolean;
  is_walk_in: Generated<boolean>;
  last_modified: Timestamp;
  metadata: Generated<Json>;
  notes: string;
  patient_id: string;
  provider_id: string | null;
  reason: string;
  server_created_at: Timestamp;
  status: string;
  timestamp: Timestamp;
  updated_at: Timestamp;
  user_id: string;
}

export interface ClinicDepartments {
  additional_capabilities: Generated<Json | null>;
  can_dispense_medications: Generated<boolean>;
  can_perform_imaging: Generated<boolean>;
  can_perform_labs: Generated<boolean>;
  clinic_id: string;
  code: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  metadata: Generated<Json>;
  name: string;
  server_created_at: Generated<Timestamp | null>;
  status: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface ClinicInventory {
  batch_expiry_date: Timestamp | null;
  batch_id: string;
  batch_number: string | null;
  clinic_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  drug_id: string;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  last_counted_at: Timestamp | null;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  quantity_available: number;
  recorded_by_user_id: string | null;
  reserved_quantity: Generated<number | null>;
  server_created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Clinics {
  address: string | null;
  attributes: Generated<string[]>;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: string;
  is_archived: Generated<boolean>;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  metadata: Generated<Json>;
  name: string | null;
  server_created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface DispensingRecords {
  batch_id: string | null;
  clinic_id: string;
  created_at: Generated<Timestamp>;
  days_supply: number | null;
  deleted_at: Timestamp | null;
  dispensed_at: Timestamp;
  dispensed_by: string;
  dosage_instructions: string | null;
  drug_id: string;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  patient_id: string;
  prescription_item_id: string | null;
  quantity_dispensed: number;
  recorded_by_user_id: string | null;
  server_created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface DrugBatches {
  batch_number: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  drug_id: string;
  expiry_date: Timestamp;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  is_quarantined: Generated<boolean | null>;
  last_modified: Generated<Timestamp>;
  manufacture_date: Timestamp | null;
  metadata: Generated<Json>;
  purchase_currency: Generated<string | null>;
  purchase_price: Numeric | null;
  quantity_received: number;
  quantity_remaining: number;
  received_date: Timestamp;
  recorded_by_user_id: string | null;
  server_created_at: Generated<Timestamp>;
  supplier_name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DrugCatalogue {
  barcode: Generated<string | null>;
  brand_name: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  dosage_quantity: Numeric;
  dosage_units: string;
  form: string;
  generic_name: string;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  is_controlled: Generated<boolean | null>;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  manufacturer: string | null;
  max_stock_level: number | null;
  metadata: Generated<Json>;
  min_stock_level: Generated<number | null>;
  notes: string | null;
  recorded_by_user_id: string | null;
  requires_refrigeration: Generated<boolean | null>;
  route: string;
  sale_currency: string | null;
  sale_price: Generated<Numeric>;
  server_created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface EventForms {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: string | null;
  form_fields: Generated<Json>;
  id: string;
  is_deleted: Generated<boolean | null>;
  is_editable: Generated<boolean | null>;
  is_snapshot_form: Generated<boolean | null>;
  language: Generated<string>;
  last_modified: Generated<Timestamp | null>;
  metadata: Generated<Json>;
  name: string | null;
  server_created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface Events {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  event_type: string | null;
  form_data: Generated<Json>;
  form_id: string | null;
  id: string;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  metadata: Generated<Json>;
  patient_id: string | null;
  server_created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
  visit_id: string | null;
}

export interface InventoryTransactions {
  balance_after: number;
  batch_id: string | null;
  clinic_id: string;
  created_at: Generated<Timestamp>;
  drug_id: string;
  id: Generated<string>;
  performed_by: string | null;
  quantity: number;
  reason: string | null;
  reference_id: string | null;
  reference_type: string | null;
  timestamp: Timestamp;
  transaction_type: string;
  updated_at: Generated<Timestamp>;
}

export interface PatientAdditionalAttributes {
  attribute: string;
  attribute_id: string;
  boolean_value: boolean | null;
  created_at: Timestamp;
  date_value: Timestamp | null;
  deleted_at: Timestamp | null;
  id: string;
  is_deleted: boolean;
  last_modified: Timestamp;
  metadata: Generated<Json>;
  number_value: number | null;
  patient_id: string;
  server_created_at: Timestamp;
  string_value: string | null;
  updated_at: Timestamp;
}

export interface PatientAllergies {
  allergen_code: string | null;
  allergen_code_system: string | null;
  allergen_label: string | null;
  allergy_type: string | null;
  clinical_status: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  end_date: Timestamp | null;
  id: string;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  onset_date: Timestamp | null;
  patient_id: string;
  recorded_by_user_id: string | null;
  server_created_at: Generated<Timestamp>;
  severity: string | null;
  updated_at: Generated<Timestamp>;
  verification_status: string;
}

export interface PatientAllergyReactions {
  allergy_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  reaction_manifestation_code: string | null;
  reaction_manifestation_label: string;
  server_created_at: Generated<Timestamp>;
  severity: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PatientObservations {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  observation_code: string;
  observation_code_system: string | null;
  observation_label: string | null;
  patient_id: string;
  recorded_by_user_id: string | null;
  server_created_at: Generated<Timestamp>;
  timestamp: Timestamp;
  updated_at: Generated<Timestamp>;
  value_boolean: boolean | null;
  value_code: string | null;
  value_datetime: Timestamp | null;
  value_numeric: Numeric | null;
  value_string: string | null;
  value_unit: string | null;
  visit_id: string | null;
}

export interface PatientProblems {
  clinical_status: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  end_date: Timestamp | null;
  id: string;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  onset_date: Timestamp | null;
  patient_id: string;
  problem_code: string;
  problem_code_system: string;
  problem_label: string;
  recorded_by_user_id: string | null;
  server_created_at: Generated<Timestamp>;
  severity_score: number | null;
  updated_at: Generated<Timestamp>;
  verification_status: string;
  visit_id: string | null;
}

export interface PatientRegistrationForms {
  clinic_id: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  fields: Generated<Json>;
  id: string;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  metadata: Generated<Json>;
  name: Generated<string>;
  server_created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface Patients {
  additional_data: Generated<Json>;
  camp: string | null;
  citizenship: string | null;
  created_at: Generated<Timestamp | null>;
  date_of_birth: Timestamp | null;
  deleted_at: Timestamp | null;
  external_patient_id: string | null;
  given_name: string | null;
  government_id: string | null;
  hometown: string | null;
  id: string;
  image_timestamp: Timestamp | null;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  last_modified_by: string | null;
  metadata: Generated<Json>;
  phone: string | null;
  photo_url: string | null;
  primary_clinic_id: string | null;
  server_created_at: Generated<Timestamp | null>;
  sex: string | null;
  surname: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface PatientTobaccoHistory {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  packs_per_day: Numeric | null;
  patient_id: string;
  quit_date: Timestamp | null;
  recorded_by_user_id: string | null;
  server_created_at: Generated<Timestamp>;
  smoking_status: string;
  start_date: Timestamp | null;
  type: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PatientVitals {
  bmi: Numeric | null;
  bp_position: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  diastolic_bp: number | null;
  event_id: string | null;
  heart_rate: number | null;
  height_cm: Numeric | null;
  id: string;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  oxygen_saturation: Numeric | null;
  pain_level: number | null;
  patient_id: string;
  pulse_rate: number | null;
  recorded_by_user_id: string | null;
  respiratory_rate: number | null;
  server_created_at: Generated<Timestamp>;
  systolic_bp: number | null;
  temperature_celsius: Numeric | null;
  timestamp: Timestamp;
  updated_at: Generated<Timestamp>;
  visit_id: string | null;
  waist_circumference_cm: Numeric | null;
  weight_kg: Numeric | null;
}

export interface PrescriptionItems {
  clinic_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  dosage_instructions: string;
  drug_id: string;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  item_status: Generated<string | null>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  notes: string | null;
  patient_id: string;
  prescription_id: string;
  quantity_dispensed: Generated<number | null>;
  quantity_prescribed: number;
  recorded_by_user_id: string | null;
  refills_authorized: Generated<number | null>;
  refills_used: Generated<number | null>;
  server_created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Prescriptions {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  expiration_date: Timestamp | null;
  filled_at: Timestamp | null;
  filled_by: string | null;
  id: string;
  is_deleted: Generated<boolean>;
  items: Generated<Json>;
  last_modified: Generated<Timestamp>;
  metadata: Generated<Json>;
  notes: Generated<string>;
  patient_id: string;
  pickup_clinic_id: string;
  prescribed_at: Generated<Timestamp>;
  priority: Generated<string | null>;
  provider_id: string;
  server_created_at: Generated<Timestamp>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  visit_id: string | null;
}

export interface Resources {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: string | null;
  hash: string | null;
  id: string;
  is_deleted: Generated<boolean>;
  last_modified: Generated<Timestamp | null>;
  mimetype: string;
  server_created_at: Generated<Timestamp | null>;
  store: string;
  store_version: string;
  updated_at: Generated<Timestamp | null>;
  uri: string;
}

export interface ServerVariables {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: string;
  key: string;
  updated_at: Generated<Timestamp | null>;
  value_data: Buffer | null;
  value_hash: Generated<string | null>;
  value_type: string;
}

export interface StringContent {
  content: string | null;
  deleted_at: Timestamp | null;
  id: string;
  is_deleted: Generated<boolean | null>;
  language: string | null;
  last_modified: Generated<Timestamp | null>;
  server_created_at: Generated<Timestamp | null>;
  updated_at: Timestamp | null;
}

export interface StringIds {
  deleted_at: Timestamp | null;
  id: string;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  server_created_at: Generated<Timestamp | null>;
}

export interface Tokens {
  expiry: Generated<Timestamp>;
  token: string;
  user_id: string | null;
}

export interface UserClinicPermissions {
  can_delete_records: Generated<boolean | null>;
  can_edit_records: Generated<boolean | null>;
  can_register_patients: Generated<boolean | null>;
  can_view_history: Generated<boolean | null>;
  clinic_id: string;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  id: Generated<string>;
  is_clinic_admin: Generated<boolean | null>;
  last_modified_by: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface Users {
  clinic_id: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  email: string;
  hashed_password: string;
  id: string;
  instance_url: string | null;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  name: string;
  role: string;
  server_created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface Visits {
  check_in_timestamp: Timestamp | null;
  clinic_id: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: string;
  is_deleted: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  metadata: Generated<Json>;
  patient_id: string | null;
  provider_id: string | null;
  provider_name: string | null;
  server_created_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface DB {
  alembic_version: AlembicVersion;
  app_config: AppConfig;
  appointments: Appointments;
  clinic_departments: ClinicDepartments;
  clinic_inventory: ClinicInventory;
  clinics: Clinics;
  dispensing_records: DispensingRecords;
  drug_batches: DrugBatches;
  drug_catalogue: DrugCatalogue;
  event_forms: EventForms;
  events: Events;
  inventory_transactions: InventoryTransactions;
  patient_additional_attributes: PatientAdditionalAttributes;
  patient_allergies: PatientAllergies;
  patient_allergy_reactions: PatientAllergyReactions;
  patient_observations: PatientObservations;
  patient_problems: PatientProblems;
  patient_registration_forms: PatientRegistrationForms;
  patient_tobacco_history: PatientTobaccoHistory;
  patient_vitals: PatientVitals;
  patients: Patients;
  prescription_items: PrescriptionItems;
  prescriptions: Prescriptions;
  resources: Resources;
  server_variables: ServerVariables;
  string_content: StringContent;
  string_ids: StringIds;
  tokens: Tokens;
  user_clinic_permissions: UserClinicPermissions;
  users: Users;
  visits: Visits;
}
