// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logger from "./Logger.res.mjs";

let Logger$1 = {
  log: Logger.log,
  warn: Logger.warn,
  error: Logger.error,
  info: Logger.info
};

export {
  Logger$1 as Logger,
}
/* Logger Not a pure module */
