// Generated by ReScript, PLEASE EDIT WITH CARE


function noop(_args) {
  
}

let match = (process.env.NODE_ENV === "production");

let isDev = match !== undefined;

let log = isDev ? prim => {
    console.log(prim);
  } : noop;

let warn = isDev ? prim => {
    console.warn(prim);
  } : noop;

let error = isDev ? prim => {
    console.error(prim);
  } : noop;

let info = isDev ? prim => {
    console.info(prim);
  } : noop;

export {
  noop,
  isDev,
  log,
  warn,
  error,
  info,
}
/* match Not a pure module */
