name: Fly Deployments
on:
  push:
    branches:
      - next # will change later
jobs:
  fly-io-web-server:
    name: deploy web server to fly.io
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-live-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy App From Monorepo
        run: flyctl deploy --remote-only -c apps/web/fly.prod.toml --dockerfile apps/web/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_WEB_SERVER }}
